package index

import "math"

// Decision is the freshness verdict for a single file when comparing a
// previously stored FileEntry against a freshly computed FileSig.
type Decision int

const (
	// DecisionNoop means the file is unchanged; nothing to do.
	DecisionNoop Decision = iota

	// DecisionUpdateMechanical means the content changed but only in a
	// way that does not warrant rewriting the summary (small middle
	// edit). Update the hashes and word count, keep the summary.
	DecisionUpdateMechanical

	// DecisionRegenerate means the file changed materially (intro,
	// conclusion, or significant body shift) and the summary should be
	// regenerated by an LLM on the next index pass.
	DecisionRegenerate

	// DecisionNew means there is no previous entry for this path.
	DecisionNew

	// DecisionDeleted means the previous entry's path is gone from disk.
	DecisionDeleted

	// DecisionRename means a deleted entry was matched by content_hash
	// to a new file at a different path; the summary should be ported.
	DecisionRename
)

// String returns a stable, human-readable name for the decision.
func (d Decision) String() string {
	switch d {
	case DecisionNoop:
		return "noop"
	case DecisionUpdateMechanical:
		return "update_mechanical"
	case DecisionRegenerate:
		return "regenerate"
	case DecisionNew:
		return "new"
	case DecisionDeleted:
		return "deleted"
	case DecisionRename:
		return "rename"
	default:
		return "unknown"
	}
}

// WordsRegenerateThreshold is the |Δwords| / max(prev, cur) ratio at or
// above which a body change forces summary regeneration even when the
// head and tail windows are stable. PROPOSAL2.md spec: 10%.
const WordsRegenerateThreshold = 0.10

// Decide compares a stored FileEntry against a fresh signature and
// returns the appropriate Decision.
//
//   - prev == nil → DecisionNew.
//   - cur == nil → DecisionDeleted.
//   - content_hash unchanged → DecisionNoop.
//   - head_hash or tail_hash changed → DecisionRegenerate.
//   - |Δwords| / words ≥ 10% → DecisionRegenerate.
//   - otherwise → DecisionUpdateMechanical.
func Decide(prev *FileEntry, cur *FileSig) Decision {
	if prev == nil && cur == nil {
		return DecisionNoop
	}
	if prev == nil {
		return DecisionNew
	}
	if cur == nil {
		return DecisionDeleted
	}
	if prev.ContentHash == cur.ContentHash {
		return DecisionNoop
	}
	if prev.HeadHash != cur.HeadHash || prev.TailHash != cur.TailHash {
		return DecisionRegenerate
	}
	if wordsDriftedSignificantly(prev.Words, cur.Words) {
		return DecisionRegenerate
	}
	return DecisionUpdateMechanical
}

func wordsDriftedSignificantly(prev, cur int) bool {
	denom := prev
	if cur > denom {
		denom = cur
	}
	if denom == 0 {
		// Both zero → no drift; either zero with the other non-zero is
		// 100% drift. The general formula handles this correctly via the
		// absolute fall-through below.
		return prev != cur
	}
	delta := math.Abs(float64(prev - cur))
	return delta/float64(denom) >= WordsRegenerateThreshold
}

// MatchRename checks whether a freshly observed FileSig matches the
// content_hash of one of the just-deleted entries. If it does, the
// caller should port the deleted entry's summary onto the new path
// (DecisionRename semantics). Returns the matched path and entry, or
// ("", FileEntry{}, false) if no rename match is found.
func MatchRename(sig FileSig, deleted map[string]FileEntry) (string, FileEntry, bool) {
	for path, entry := range deleted {
		if entry.ContentHash != "" && entry.ContentHash == sig.ContentHash {
			return path, entry, true
		}
	}
	return "", FileEntry{}, false
}
